#let Tm = $upright(bold("Tm"))$
#let Ty = $upright(bold("Ty"))$
#let Eq = $upright(bold("Eq"))$
#let Id = $upright(bold("Id"))$
#let Void = $upright(bold("Void"))$
#let absurd = $upright("absurd")$
#let Bool = $upright(bold("Bool"))$
#let tt = $upright(bold("tt"))$
#let ff = $upright(bold("ff"))$
#let btrue = $upright(bold("true"))$
#let bfalse = $upright(bold("false"))$
#let inl = $upright("inl")$
#let inr = $upright("inr")$
#let zero = $upright("zero")$
#let succ = $upright("succ")$
#let hy = $tack.r$
#let hyu = $attach(tack.r, br: u)$
#let hyp = $attach(tack.r, br: +)$
#let hyt = $attach(tack.r, br: t)$
#let type = $upright("type")$
#let sq = $upright(bold("q"))$
#let sp = $upright(bold("p"))$
#let Unit = $upright(bold("Unit"))$
#let El = $upright(bold("El"))$
#let code = $upright(bold("code"))$
#let UU = $upright(bold("U"))$
#let HProp = $upright(bold("HProp"))$
#let rec = $upright(bold("rec"))$
#let ind = $upright(bold("ind"))$
#let lift = $upright(bold("lift"))$
#let uni = $upright(bold("uni"))$
#let sym = $upright("sym")$
#let trans = $upright("trans")$
#let cong = $upright("cong")$
#let subst = $upright("subst")$
#let jrule = $upright(bold("J"))$
#let uniq = $upright("uniq")$
#let gap = $#h(0.3em)$
#let refl = $upright(bold("refl"))$
#let equiv = $tilde.eq$
#let idtoequiv = $upright("idtoequiv")$
#let isotoid = $upright("isotoid")$
#let ua = $upright("ua")$
#let coe = $upright("coe")$
#let coh = $upright("coh")$
#let sqr = square(inset: 0.2em)[#square(size: 0.3em)]
#let trir = $triangle.stroked.r$
#let subt = $prec.curly.eq$